<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Promise</title>
</head>
<body>
    <script>

         /*
            Exercícios 1 :

            Refaça os exercícios do arquivo callbacks.html utilizando Promises. */

            
            function somar(n1, n2) {
                return new Promise((resolve, reject) => {
                    setTimeout(() => {
                        const resultado = n1 + n2;

                        if (resultado % 2 !== 0) {
                            reject(new Error("O valor é ímpar"));
                        } else {
                            resolve(resultado);
                        }
                    }, 2000);
                })
            }

            somar(1, 2)
                .then(resultado => console.log(`A operação foi bem sucedida! O número ${resultado} é par`))
                .catch(error => console.log(`A operação falhou! ${error.message}`));

        /* 2) Exercício : Crie uma função dobrarEm5Segundos(numero, cb) que dobre o valor de um número após 5 segundos. Se o valor recebido não for um número
        ele irá chamar a cb passando um erro. 

        callback(error, result) => Se um erro for passado irá mostrar a mensagem: "A operação falhou! [mensagem do erro]".
        Senão, irá mostrar a mensagem: "A operação foi bem sucedida! O resultado é [result]". */

        function dobrarEm5Segundos(numero, cb) {
            setTimeout(() => {
                if (isNaN(numero)) {
                    cb(new TypeError("O valor precisa ser numérico"));
                } else {
                    const dobro = numero * 2;
                    cb(null, dobro);
                }
            }, 5000);
        }

        dobrarEm5Segundos("a", (error, resultado) => {
            if (error) {
                console.log(`A operação falhou! ${error.message}.`);
            } else {
                console.log(`A operação foi bem sucedida! O resultado é ${resultado}.`);
            }
        }); 

        /* 3) Exercicio: Crie uma função obtemUsuarioPeloNome(nome, cb) quee verifica após 3 segundos se o nome faz parte do vetor: */
        [
            {
                nome: "João",
                idade: 25,
                email: "joao@email.com"
            },
            {
                nome: "Pedro",
                idade: 33,
                email: "pedro@email.com"
            },
            {
                nome: "Marcos",
                idade: 16,
                email: "marcos@email.com"
            }
        ]
        
        /* Se o nome informado não estiver no vetor a função deverá chamar a callback passando um UserNotFoundError com a mensagem "Usuário não está cadastrado".
        Caso o nome informado esteja cadastrado na lista a callback deve ser chamada passando as informações do usuário com aquele nome. 

        cb(error) -> Ocorreu um erro! [mensagem do erro]
        cb(success) -> Usuário encontrado: */
                       nome: [nome do usuário]
                       idade: [idade do usuário]
                       email: [email do usuário]
        
        const listaPessoas = [
            {
                nome: "João",
                idade: 25,
                email: "joao@email.com"
            },
            {
                nome: "Pedro",
                idade: 33,
                email: "pedro@email.com"
            },
            {
                nome: "Marcos",
                idade: 16,
                email: "marcos@email.com"
            }
        ];

        class UserNotFoundError extends Error {
            constructor(message) {
                super(message);
                this.name = "UserNotFoundError";
            }
        }

        function obtemUsuarioPeloNome(nome, cb) {
            setTimeout(() => {
                const usuario = listaPessoas.find(pessoa => pessoa.nome === nome);

                if (!usuario) {
                    cb(new UserNotFoundError("Usuário não está cadastrado"));
                } else {
                    cb(null, usuario);
                }
            }, 3000);            
        }

        obtemUsuarioPeloNome("Pedro", (error, pessoa) => {
            if (error) {
                console.log(`Ocorreu um erro! ${error.message}.`);
            } else {
                console.log(`Usuário encontrado:\nnome: ${pessoa.nome}\nidade: ${pessoa.idade}\nemail: ${pessoa.email}.`);
            }
        }); 
            
    </script>
</body>
</html>